name: pnpm Storybook Deploy

on:
  push:
    branches:
      - main # or your desired branch

jobs:
  build-storybook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # or your desired Node.js version
      - name: Install dependencies
        run: pnpm install
      - name: Build Storybook
        run: pnpm run storybook build

  deploy-storybook:
    needs: build-storybook
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          folder: storybook-static # Output directory from build-storybook
